name: "Build Solution"
description: "Execute MSBuild with desired settings."
inputs:
      build-mode:
        description: 'Solution build mode passed to MSBuild.'
        required: true

      version:
        description: 'Version number to refer to this build and its assets, in the form `major.minor.build`.'
        required: true

      compile-langs:
        description: 'Install the Multilingual App Toolkit extension, so that languages are compiled.'
        required: true

runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restore Packages
      working-directory: WinNUT_V2
      shell: pwsh
      run: msbuild $env:SLN_DIR -t:restore
    - name: Install Multilingual App Toolkit extension
      if: inputs.compile-langs == 'true'
      uses: microcompiler/install-vsix@db1f973c3d24d1ddc0c38f14d0e1e3a85b2ccb21
      with:
        packagename: 'dts-publisher.mat2022'
    - name: Build solution
      shell: pwsh
      working-directory: WinNUT_V2
      run: >
        msbuild WinNUT_V2.sln -nologo
        -property:Configuration=${{ inputs.build-mode }}
        -property:Version=${{ inputs.version }}