name: build-debug

on:
  workflow_dispatch:

  pull_request:
    branches: Dev-2.2
    paths:
    - '**.vb'
    - '**.vbproj'

jobs:
  build-debug:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build solution in Debug configuration
        uses: ./.github/actions/build-solution
        with:
          build-mode: "Debug"
          version: "${{ vars.PRERELEASE_VERSION }}.*"