# Core building functionality, intended to be called from more specific workflows.
name: build-solution

on:
  workflow_call:
    inputs:
      buildMode:
        description: 'Solution build mode passed to MSBuild.'
        required: true
        type: string

      version:
        description: 'Version number to refer to this build and its assets, in the form `major.minor.build`.'
        required: true
        type: string

      compileLangs:
        description: 'Install the Multilingual App Toolkit extension, so that languages are compiled.'
        required: true
        type: boolean

env:
  DOTNET_VERSION: '4.8'
  SLN_DIR: WinNUT_V2

jobs:
  build:
    name: build-[${{ inputs.buildMode }}]v${{ inputs.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    # Install the MAT extension for multilingual compilation if requested.
    - name: Install Multilingual App Toolkit extension
      if: ${{ inputs.compileLangs }}
      uses: microcompiler/install-vsix@db1f973c3d24d1ddc0c38f14d0e1e3a85b2ccb21
      with:
        packagename: 'dts-publisher.mat2022'

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore Packages
      run: msbuild $env:SLN_DIR -t:restore

    # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
    - name: Build solution
      run: >
        msbuild $env:SLN_DIR\WinNUT_V2.sln -nologo
        -property:Configuration=${{ inputs.buildMode }}
        -property:Version=${{ inputs.version }}